### ISSUE TITLE
Attribute changes delta visualization problem

### ISSUE THREAD

**Issue by manojkeshava** [eMoflon/kaleidoscope-ui#3]
When there are attribute changes the visualization breaks. The error looks like
![visualization_error](https://user-images.githubusercontent.com/18480366/36509677-bed3c79e-1760-11e8-99f2-be544b860ac5.PNG)

I am also attaching the delta model which I used when I landed in this error.

[ChangeAttributeDeleteAndAddPostObject.zip](https://github.com/eMoflon/kaleidoscope-ui/files/1746015/ChangeAttributeDeleteAndAddPostObject.zip)

Thanks,
Manoj

**Comment by anthonyanjorin** [comment]
Please check if this works now with the latest update site.  Kindly use the visualisation for all your deltas and report further problems.
